### ISSUE TITLE
feature request: @toolchains_protoc//:protoc target

### ISSUE THREAD

**Issue by aran** [alexeagle/toolchains_protoc#4]
`rules_rust` has `rust_prost_toolchain`: https://bazelbuild.github.io/rules_rust/flatten.html#rust_prost_toolchain which wants a `proto_compiler` option. That can currently be `@protobuf//:protoc`. 

It would be useful if I could drop in `@toolchains_protoc//:protoc` there.

**Comment by alexeagle** [comment]
The latter is correct, it should be similar to https://github.com/bazelbuild/rules_go/issues/3895

I'll file with rules_rust.

**Comment by aran** [comment]
Should be solved elsewhere per above

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/rules_rust/issues/2627
